services:
  go_app:
    container_name: go_app
    image: mealplanner:1.0.0
    build: .
    environment:
        DATABASE_URL: "host=go_db user=postgres password=mealplannerpgadmin dbname=mealplanner_db sslmode=disable"
    ports:
      - "4000:4000"
    networks:
      - meal-planner
    depends_on:
      - go_db
    

  go_db:
    container_name: go_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: mealplannerpgadmin
      POSTGRES_USER: postgres
      POSTGRES_DB: mealplanner_db
    ports:
      - "5433:5432"
    networks:
      - meal-planner
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
